# Generated by Django 2.1.2 on 2018-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='KYC',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
