# Generated by Django 2.1.2 on 2018-12-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181211_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
