# Generated by Django 2.1.2 on 2018-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='NGN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='USD',
            field=models.FloatField(),
        ),
    ]
