# Generated by Django 2.1.2 on 2018-12-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registered_user', '0002_auto_20181203_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGN', models.FloatField()),
                ('USD', models.FloatField()),
                ('volume', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfectMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGN', models.FloatField()),
                ('USD', models.FloatField()),
                ('volume', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ripple',
            name='NGN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ripple',
            name='USD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ripple',
            name='volume',
            field=models.FloatField(),
        ),
    ]
