# Generated by Django 2.2.2 on 2019-07-18 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registered_user', '0006_auto_20190708_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_coin', models.CharField(max_length=100)),
                ('sell_amount', models.FloatField(max_length=100)),
                ('sell_amount_currency', models.CharField(max_length=20)),
                ('sell_amount_in_ngn', models.FloatField()),
                ('sell_order_id', models.CharField(default='ABCDef', max_length=20)),
                ('sell_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_coin', models.CharField(max_length=100)),
                ('buy_amount', models.FloatField(max_length=100)),
                ('buy_amount_currency', models.CharField(max_length=20)),
                ('buy_amount_in_ngn', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='ABCD', max_length=20)),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
