# Generated by Django 2.2.2 on 2019-07-19 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0007_buyorders_sellorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyorders',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellorders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorders',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
