# Generated by Django 2.1.2 on 2018-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfectMoneyBuyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfectMoneySellPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RippleBuyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RippleSellPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Ethereum',
            new_name='BitCoinBuyPrice',
        ),
        migrations.RenameModel(
            old_name='PerfectMoney',
            new_name='BitCoinSellPrice',
        ),
        migrations.RenameModel(
            old_name='BitCoin',
            new_name='EthereumBuyPrice',
        ),
        migrations.RenameModel(
            old_name='Ripple',
            new_name='EthereumSellPrice',
        ),
    ]
